name: Docker CI/CD

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Budowanie obrazu Docker
        run: docker build -t lab4 .

      - name: Uruchomienie kontenera
        run: docker run -d --name lab4-container -p 8080:80 lab4

      - name: Poczekaj na start kontenera
        run: sleep 5

      - name: Sprawdzenie kontenera
        run: docker ps

      - name: Test aplikacji
        run: curl -v http://localhost:8080